### ISSUE TITLE
Linking clips in FCP XML

### ISSUE THREAD

**Issue by ethan-ou** [PixarAnimationStudios/OpenTimelineIO#761] opened 2020-07-17 10:49 UTC
I noticed while looking through the source code that [link tags are automatically removed](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/master/src/py-opentimelineio/opentimelineio/adapters/fcp_xml.py#L466-L473) to avoid errors when doing roundtrips with XML's. I'm wondering if there's a way for users to override this behaviour.

With my own research, I'm guessing this was disabled was because of the generated id system in these XML's. For linking to work, each file needs a metadata tag with its own `@id` that's auto-generated when the XML is exported. If the id's change, the links break. At the same time, I'm thinking it should be possible for the user to update these links programmatically if they choose.

For those unfamiliar, an example of a link in a clip:

```python
otio.schema.Clip(
    name='C0001',
    media_reference=video_clip_1,
    metadata={"fcp_xml": {
                "@id": "clipitem-1",
                "link": [
                  {
                    "clipindex": "1",
                    "linkclipref": "clipitem-1",
                    "mediatype": "video",
                    "trackindex": "1"
                  },
                  {
                    "clipindex": "1",
                    "groupindex": "1",
                    "linkclipref": "clipitem-3",
                    "mediatype": "audio",
                    "trackindex": "1"
                  },
                  {
                    "clipindex": "1",
                    "groupindex": "1",
                    "linkclipref": "clipitem-5",
                    "mediatype": "audio",
                    "trackindex": "2"
                  }
                ]
              }}
  )
```

**Comment by reinecke** [comment] 2020-07-17 21:26
Hi @ethan-ou!
This is a tough one. The FCP XML adapter is written to do a best-effort at preserving and round-tripping anything it can (ids included). The difficulty with linking is that it's incredibly easy for the timeline to manipulated in otio in such a way that it would result in seemingly random linking of clips together. I worry the unexpected behavior would cause a lot of frustration in users.

If you want to author these links, I believe the example metadata dict you provided should work pretty well. I'm guessing the issue is that you'd like to also preserve on input so you know which links existed. Unfortunately, I'm not sure I can think of a way to do that which would prevent people from unknowingly creating broken files. I suppose the adapter could adopt some naming convention (similar to the `@` prefix for xml attributes) that denotes a piece of data came from the input, but will be skipped on output. This would allow you to crawl the timeline using `each_clip`, find the prefixed keys, and restore the values to un-prefixed keys so they'd be written on output. You'd just have to be careful that the manipulations you'd done in that context won't cause any ID conflicts or remappings.

I think the real issue is that OTIO doesn't model clip linking. #343 looks like it might be the closest issue we have for that. If OTIO did support linking clips across tracks, that would allow predictable translation behavior. This is something I think we're interested in doing, but has some challenges.

**Comment by reinecke** [comment] 2020-07-17 21:29
To add, for a little more background, here is some recent discussion in the ASWF slack on some of the challenges: https://academysoftwarefdn.slack.com/archives/CMQ9J4BQC/p1594647168105900

**Comment by ethan-ou** [comment] 2020-07-20 01:39
Thanks @reinecke for the detailed response! The edit library concept (#711) sounds like it's the best place to handle groupings so I look forward to seeing how that turns out.

**Comment by ssteinbach** [comment] 2020-08-19 00:19
@ethan-ou can we close this issue for now in favor of going through a future edit protocol type system?  or would you prefer to leave this issue open for now?

**Comment by ethan-ou** [comment] 2020-08-19 00:20
We can close it. Thanks for the clarification.

**Closed** 2020-08-19 00:20 UTC
