### ISSUE TITLE
Resolve installation into Blender

### ISSUE THREAD

**Issue by meshula** [PixarAnimationStudios/OpenTimelineIO#987] opened 2021-06-11 17:39 UTC
This issue is to track building OTIO for installation into Blender, and also the creation of wheels that Blender can consume.

**Comment by JeanChristopheMorinPerso** [comment] 2021-06-12 21:13
> From my understanding the reason this did not work for Blender was that its Python development artifacts (the include and lib) dir were not installed in a standard location.

Blender on Windows (I wont talk about Linux since I don't know the situation there) doesn't ship with the Python headers. See https://developer.blender.org/T74470 and https://blender.community/c/rightclickselect/gtfbbc/ . So that is one problem on his own.

**Comment by JeanChristopheMorinPerso** [comment] 2021-06-12 22:28
@rogernelson I looked more deeply at Pybind11 cmake files and `PYTHON_EXECUTABLE` and `PYBIND11_FINDPYTHON`  are not mutually exclusive.

If `PYBIND11_FINDPYTHON`  it will call `pybind11NewTools.cmake` (see https://github.com/pybind/pybind11/blob/e08a58111dbea38d667b209f7543864d51a3b185/tools/pybind11Common.cmake#L195-L200), then if `PYTHON_EXECUTABLE` is not defined, it does some logic for venv, conda and GitHub Actions. But if `PYTHON_EXECUTABLE` is present, then it uses pre cmake 3.12 `FindPythonInterp` (see https://github.com/pybind/pybind11/blob/e08a58111dbea38d667b209f7543864d51a3b185/tools/FindPythonLibsNew.cmake#L71,L98).

Anyway, here it doesn't matter much if it's mutually exclusive or not I think. What matter is controlling which python version is used. On that front, I noticed that CMake's own `FindPython` doesn't understand `PYTHON_EXECUTABLE`. It only seems to understand `Python_EXECUTABLE`  while pybind11 uses `PYTHON_EXECUTABLE`, which leads to confusion (notice the different in cap letters)

So, if we use want to support all cases actually supported by CMake's `FindPython` (while using CMake 3.20+), we can use `find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)` if we replace `PYTHON_EXECUTABLE` by `Python_EXECUTABLE` in our `setup.py` file. We won't need to bring back `PYBIND11_FINDPYTHON`. And this will rely on the fact that if pybind11 sees that `Python_FOUND` is set, then it won't try to find python and will simply reuse the existing python targets (https://github.com/pybind/pybind11/blob/e08a58111dbea38d667b209f7543864d51a3b185/tools/pybind11Common.cmake#L196, https://pybind11.readthedocs.io/en/stable/compiling.html#findpython-mode).

I still have some more tests to do for a bunch of cases, but so far it looks quite good. Cases to be tested:
* `manylinux` docker images. (Linux only)
* Executing `/path/to/python3.7 setup.py bdist_wheel`, make sure it's not in `PATH` and also make sure a more recent version of python (for example 3.9) is present in `PATH`. (All platforms)
* Executing `/path/to/python3.7 -m pip install . --user`, make sure it's not in `PATH` and also make sure a more recent version of python (for example 3.9) is present in `PATH`. (All platforms)
* Executing `/path/to/python3.7 -m pip wheel .`, make sure it's not in `PATH` and also make sure a more recent version of python (for example 3.9) is present in `PATH`. (All platforms)
* Execute `python setup.py bdist_wheel` from inside a virtualenv. (all platforms)
* Execute cmake while making sure Python is in `PATH` (it's great when we can just execute cmake and things just work). See how it reacts if a newer version of python is present in `PATH` before or after the Python version we want.
* Try with Blender on Windows and Linux (just to confirm that [my previous tests](https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/957#issuecomment-841703807) still work)
* Test with RV's Python (I don't have access to RV right now, so once I've tested all cases, I could push my changes in my fork and @Roger Nelson you could test it?)

Note that I persist to try to use `find_package` because if it works, then we can basically sit on the shoulders of a CMake to make sure we support future cases and fixes. It also handles quite a lot more cases than what Pybind11 can handle. Technically we could just use `PYBIND11_FINDPYTHON` which basically calls `find_package(Python REQUIRED COMPONENTS Interpreter Development)` but the problem is that they request the `Development` component, which implies that they require the Python library (.so, dll, etc) to be present, which is not present case for the `manylinux` docker container. So we have to call `find_package(Python REQUIRED COMPONENTS Interpreter Development.Module` (`Development.Module` instead of `Development`).

I hope what I just wrote makes sense. Let me know if it's not clear or have any questions or concerns.

**Comment by JeanChristopheMorinPerso** [comment] 2021-06-12 22:37
Regarding RV's `sysconfig` wrong behavior @rogernelson , that should get fixed in RV :wink: . It always annoyed me. `sysconfig` should always return paths that exist and are valid. When `sysconfig` returns wrong values, a bunch a tools in the Python ecosystem just don't work.

**Comment by brechtvl** [comment] 2021-06-13 13:24
I don't fully understand the context here. But for the large majority of Blender users, compiling Python modules from source is not something they are expected to be doing. The bundled Python version is not intended to be used for that, the recommendation is to use a standard Python install.

For add-ons it's most user-friendly to bundle binaries. But it would be great if OpenTimelineIO could provide wheels for Python 3.7 and 3.9 too. I think it's only 3.7 now, but Blender 2.93 and the next VFS reference platform use 3.9. As far as I know, building the wheels does not require any changes to make them compatible with Blender.

**Comment by meshula** [comment] 2021-06-13 16:54
The context is that we've been trying to build otio against Blender's bundled Python, with setup.py placing the build artifacts into the blender installation in the correct place.

The meta-context is that we want to be able to use otio within Blender.

The meta-meta-context is that the purpose of this thread is discover the right way to do this, make any changes necessary to our build, and then document how any developer can use otio in blender to create their own tools or add ons. Our initial understanding was that we need to build against Blender itself, but that's not the real goal of course.

Ultimately, I think Blender's timeline should natively deal with otio, but it's up to us to lay the groundwork for that to be possible. That part of the problem is out of scope for this thread.

**Comment by JeanChristopheMorinPerso** [comment] 2021-06-13 17:19
>But for the large majority of Blender users, compiling Python modules from source is not something they are expected to be doing.

To add to that, a large majority of the Python community is not expected to compile Python extensions (an extension being anything that is not pure python) from source.

Also this issue is for Blender, but I'm kind of "hijacking" it to make sure we support a bunch of other cases correctly as can be seen from the matrix of scenarios to be tested from my proposed change.

>The meta-meta-context is that the purpose of this thread is discover the right way to do this, make any changes necessary to our build, and then document how any developer can use otio in blender to create their own tools or add ons.

And bonus if we are able to support other "exotic" setups/environments I think without any additional effort from the OTIO side.

**Comment by JeanChristopheMorinPerso** [comment] 2021-06-14 00:16
@rogernelson You can try to build using https://github.com/JeanChristopheMorinPerso/OpenTimelineIO/tree/python_build_findpython. Let me know how it goes!

**Comment by rogernelson** [comment] 2021-06-14 13:38
@JeanChristopheMorinPerso 
I tried your branch, and it seems to do the right thing for me.

RV Python 2.7
```
-- Found Python: /Users/nelsonr/git/shotgun-rv/rv-cxx14-debug-qt5-python2.7x3.7/bin/py-interp (found version "2.7.17") found components: Interpreter Development.Module 
-- Python_INCLUDE_DIRS: /Users/nelsonr/git/shotgun-rv/rv-cxx14-debug-qt5-python2.7x3.7/python2/include/python2.7
-- Python_VERSION: 2.7.17
```

I also tried with RV and Python 3.7.6
```
-- Found Python: /Users/nelsonr/git/shotgun-rv/rv-cxx14-debug-qt5-python2.7x3.7/bin/py-interp (found version "3.7.6") found components: Interpreter Development.Module 
-- Python_INCLUDE_DIRS: /Users/nelsonr/git/shotgun-rv/rv-cxx14-debug-qt5-python2.7x3.7/python3/include/python3.7m
-- Python_VERSION: 3.7.6
```

If this same setup works for Blender, then this is great.

> Regarding RV's sysconfig wrong behavior @rogernelson , that should get fixed in RV 😉 . It always annoyed me. sysconfig should always return paths that exist and are valid. When sysconfig returns wrong values, a bunch a tools in the Python ecosystem just don't work.

I work primarily with C++, so I'm not an expert on all this Python stuff, but I agree the RV values are wrong.  Since I'm working on integrating OTIO into RV's Python, I'll see if I can tackle this too while I'm in there.

**Comment by tin2tin** [comment] 2021-06-25 05:29
> > From my understanding the reason this did not work for Blender was that its Python development artifacts (the include and lib) dir were not installed in a standard location.
> 
> Blender on Windows (I wont talk about Linux since I don't know the situation there) doesn't ship with the Python headers. See https://developer.blender.org/T74470 and https://blender.community/c/rightclickselect/gtfbbc/ . So that is one problem on his own.

If adding the python headers to Blender, you should say it out loud here: https://devtalk.blender.org/t/opentimelineio-devs-needs-bf-devs-to-solve-python-related-installation-problems/19192/14

**Closed** 2021-07-02 18:37 UTC
Labels: build, wheels
