### ISSUE TITLE
Clip rate conversion putting entire track out of sync

### ISSUE THREAD

**Issue by andrewmoore-nz** [PixarAnimationStudios/OpenTimelineIO#468] opened 2019-03-27 00:20 UTC
In doing some testing with a small scale but real world project last week, I came across a specific issue with the way frame rates are parsed from XMLs, but also a more fundamental issue with how these small bugs can effect the entire system. 

This project _(an FCP7 XML exported from a 29.97fps Premiere timeline)_ has two clips at the end of the timeline (on separate tracks) that were copied in from another timeline. Due to the way this is represented in the XML, these clips become 'Clip' objects within OTIO with a source_range duration and start_time rate of 23.976.

When it then comes to calculating the master in/out values for each clip on their respective track, a conversion has to happen to get the required 29.97fps duration from the Clip's stored 23.976 duration value, resulting in a rounding error that puts the entire track 1 frame out of sync. For example:

```
"duration": {
    "OTIO_SCHEMA": "RationalTime.1", 
    "rate": 23.976, 
    "value": 48
```
When this value is converted to 29.97fps, resulting in a value of 59.8801797602996404, this is rounded up to **60** in OTIO (or the conversion math is being over-simplified), when in Premiere it is clipped at **59**, which is what is specified in the XML:

```
<masterclipid>masterclip-11</masterclipid>
<name>TCC_VideoCard_End3.png</name>
<enabled>TRUE</enabled>
<duration>1035764</duration>
<rate>
	<timebase>24</timebase>
	<ntsc>TRUE</ntsc>
</rate>
<start>1971</start>
<end>2030</end>
<in>86312</in>
<out>86360</out>
```

This means that every clip that comes after it on the same track will be 1 frame out of sync, due the way OTIO approaches constructing a timeline based on the cumulative duration values of every clip/gap that comes before it. This can be seen very clearly here:

![OTIO_FramerateConversionSlippingWholeTrackError](https://user-images.githubusercontent.com/19657812/55040683-4b467e80-508e-11e9-9a94-17c267fc69d2.png)

This clip has shifted 1 frame in relation to its surrounding tracks, however it has not been altered or effected in Premiere at all, and its XML `<start>` & `<end>` values have not changed. It is simply that a copy of the clip in question has been placed prior to it on the timeline.

It seems to me like the logical thing to do would be to validate the source_range duration values and rates to ensure that the timeline representation is true and accurate, as the XML holds the specific, correct information that we need, it's just that the OTIO model does not. In order to accurately reflect a timeline, I would argue that there should not be any other frame rate values allowed in this situation other than the global one being used, in this case 29.97, as it requires doing a conversion which leaves itself open to error. 

Certainly a discussion point for how these ideas are approached and handled. Currently this approach is broken for some specific situations, such as this. Happy to provide further information/examples.

**Comment by ssteinbach** [comment] 2019-03-27 00:39
I'm a little confused about this point:
```When this value is converted to 29.97fps, resulting in a value of 59.8801797602996404, this is rounded up to 60 in OTIO (or the conversion math is being over-simplified), when in Premiere it is clipped at 59, which is what is specified in the XML:```

What would be doing the rounding?  The way its being displayed in Otioview?  Or when it gets reserialized out to disk?

**Comment by reinecke** [comment] 2019-03-27 00:52
In a similar case I was looking at recently, I found that OTIO was accurately translating the times from the FCP XML file, but working with those times (say to get a frame number in the right timebase) could manifest in issues similar to the one you're describing. Not sure if that is related to what you're seeing here.

I'd love to dig into this more and see if there isn't a way OTIO might be able to more gracefully deal with this. If your situation permits, would you be able to provide a reference FCP XML file and some python code demonstrating the issue?

**Comment by thecargocultnz** [comment] 2019-03-27 01:17
OK, so there are 2 important points here:

1 - While "60 frames" is the correct result in the above example - that's irrelevant. Premiere is using 59 frames of the timeline for that clip. The XML is really clear about that, and an EDL of the sequence concurs. Instead of using the start/end times provided, OTIO is using the source clip length and rate and performing acrobatics with it.

2 - If the source duration in question were not a whole-second value, we'd be in trouble for a different reason:
 00:00:00:10.0 @23.98  = 00:00:00:12.500 @29.97  - so we'd have a half frame error forever after, or we'd be forced to make a call on arbitrarily rounding that timecode value.

at the end of the day - we've been told by Premiere to insert 59 frames, but we're possibly inserting some other amount, affecting everything on the track from that point forward.

**Comment by andrewmoore-nz** [comment] 2019-03-27 03:22
@ssteinbach A little clarification regarding the point that is confusing you:

Not actually the best example to use in this particular case, given that 48 frames @ 23.976fps is conceptually the same as 60 frames @ 29.97fps. The rounding that I'm referring to is possibly a small misunderstanding on my part as to what's happening behind the scenes having not looked specifically at the math that is being used here, although it is something that Otioview is displaying incorrectly, given to the underlying conversion process.

Here's a better, more concrete example of the issue I'm seeing...

Using my test Premiere project and the clip that has been causing this issue _(a 23.976 rate clip on a 29.97 timeline)_, I can get the following result:

**Clip 1 XML:**
```
<masterclipid>masterclip-10</masterclipid>
<name>TCC_VideoCard_End3.png</name>
<enabled>TRUE</enabled>
<duration>1035764</duration>
<rate>
	<timebase>24</timebase>
	<ntsc>TRUE</ntsc>
</rate>
<start>468</start>
<end>527</end>
<in>86312</in>
<out>86360</out>
```
**Clip 1 OTIO:**
```
"OTIO_SCHEMA": "TimeRange.1", 
        "duration": {
            "OTIO_SCHEMA": "RationalTime.1", 
            "rate": 23.976, 
            "value": 48
        },
```
**Clip 2 XML:**
```
<masterclipid>masterclip-10</masterclipid>
<name>TCC_VideoCard_End3.png</name>
<enabled>TRUE</enabled>
<duration>1035764</duration>
<rate>
	<timebase>24</timebase>
	<ntsc>TRUE</ntsc>
</rate>
<start>536</start>
<end>596</end>
<in>86312</in>
<out>86360</out>
```
**Clip 2 OTIO:**
```
"OTIO_SCHEMA": "TimeRange.1", 
        "duration": {
            "OTIO_SCHEMA": "RationalTime.1", 
            "rate": 23.976, 
            "value": 48
        }, 
```

As you can see from these examples, the actual length of these clips on the 29.97 timeline is 59 frames (468 - 527) and 60 frames (536 - 596) respectively, but both have a source_range duration of 48 frames at 23.976. This makes it impossible for us to calculate the correct duration as far as I see it. Happy to provide my files for you to take a look at yourself if that helps. 

I have also been able to reproduce the first issue I was talking about in a slightly different way. Using the same clip at a length of 76 frames on the 29.97 timeline, it puts all the subsequent clips on that track out by a quarter frame, as can be seen here:

![Screen Shot 2019-03-27 at 4 08 54 PM](https://user-images.githubusercontent.com/19657812/55047798-e3eaf780-50aa-11e9-8f52-5f5a7fb637c6.png)

Both clips on the right edge of the timeline have the exact same starting timecode, but it is through the conversion to 29.97fps that a quarter frame is added to the _actual_ starting time of the top clip, thus putting it and every following clip out of sync. This is happening within Otioview, as the actual data is stored as a 23.976 value, but we're seeing the same effect in our system, and the same would be true of any system doing the proper conversion calculation.

**Comment by andrewmoore-nz** [comment] 2019-03-27 20:05
@jminor Here is a copy of the XML exported from Premiere where both of these examples have come from...

[OTIO_VaryingFrameRatesOnTimeline_SimpleTest3_190327.txt](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3015079/OTIO_VaryingFrameRatesOnTimeline_SimpleTest3_190327.txt)

_(Have just changed the file ext to allow for uploading here... all content still the same.)_

**Comment by jminor** [comment] 2019-03-27 22:03
Thanks for the test file. It looks like my proposed fix #469 helps a little, but doesn't address the main issue here. I was able to read your sample into Resolve and output it as AAF for comparison. It looks like the timing via AAF is working right, and includes a timewarp effect to deal with mixing the two rates.

I'm not familiar enough with the FCP XML format myself to fix this - hey @reinecke or @bashesenaxis can you take a look at this sample file? There is a clipitem with a mixture of timebase 24 and 30 that is confusing the adapter.

**Comment by jminor** [comment] 2019-03-27 22:17
FYI, here's the test file converted to AAF via Resolve for comparison.

[OTIO_VaryingFrameRatesOnTimeline_SimpleTest3_190327.aaf.zip](https://github.com/PixarAnimationStudios/OpenTimelineIO/files/3015446/OTIO_VaryingFrameRatesOnTimeline_SimpleTest3_190327.aaf.zip)

If you otiocat them both and the diff the resulting OTIO files you'll see something like this:
```
>                         "name": "TCC_VideoCard_End3", 
189,190c337,338
<                                 "rate": 23.976023976023978, 
<                                 "value": 61
---
>                                 "rate": 29.97002997002997, 
>                                 "value": 76
194,195c342,343
<                                 "rate": 23.976023976023978, 
<                                 "value": 86312.0
---
>                                 "rate": 29.97002997002997, 
>                                 "value": 0
203,204c351,365
```

![Screen Shot 2019-03-27 at 3 11 33 PM](https://user-images.githubusercontent.com/169599/55115870-c87bee80-50a2-11e9-92b0-2f67a0bab5bf.png)

**Comment by jminor** [comment] 2019-03-27 22:20
In the AAF adapter, we trust the Length value for each clip to be the correct computed duration for use in the resulting OTIO. If I'm reading the FCP adapter code correctly, it trusts the <in> and <out> values and subtracts them, where perhaps using the <start> and <end> would produce the correct result. Let me try that...

**Comment by jminor** [comment] 2019-03-27 22:55
Okay, that seems to be working. #469 is updated and seems to produce the right result for this test file. I've broken transitions somehow though, so there is still work to be done here. @bashesenaxis can you show me how that works?

**Comment by jminor** [comment] 2019-04-01 22:13
FYI, @reinecke is attempting a refactor of this code in order to address this.

**Comment by reinecke** [comment] 2019-04-02 18:17
Looking back at other FCP XML issues, this appears to be a duplicate of #287

**Comment by ssteinbach** [comment] 2019-05-22 21:54
Closed because of eric's note.

**Closed** 2019-05-22 21:54 UTC
